config/routes.rb
Jukebox::Application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => "users/registrations" } do
    get 'signout' => 'devise/sessions#destroy'
  end

  match '/accept_friend', :to => 'users#accept_friend'
  match '/accept_friend/:id', :to => 'users#accept_friend'

  resources :users do
    collection do
      get :friend_requests
      get :check_friend_request
      get :search
    end
    member do
    end
  end

  resources :releases

  resources :artist_members

  resources :artists do
    member do
      get   :tracks
    end
  end

  resources :tracks, :path => "songs" do
    collection do
      get   :upload
      post  :import
    end
    member do
      get   :details
    end
  end

  resources :albums do
    member do
      get   :tracks
    end
  end

  match '/albums/:name/:uqid', :to => 'albums#show'
  
  resources :playlists do
    collection do
      get   :selector
      post  :add_new
    end
    member do
      post  :add_track
      post  :remove_track
      get   :tracks
    end
  end

  match '/account', :to => 'account#index'
  match '/account/password', :to => 'account#password'
  match '/account/photo', :to => 'account#photo'
  match '/account/friends', :to => 'account#friends'
  match '/account/invite_friend', :to => 'account#invite_friend'

  match '/request_invite', :to => "pages#request_invite"
  match '/accept_invite', :to => "pages#accept_invite"
  match '/accept_invite/:token', :to => "pages#accept_invite"
  match '/home', :to => 'pages#home'
  match '/thanks', :to => 'pages#thanks'
  match '/library', :to => 'pages#home'
  match '/search', :to => 'pages#search'
  match '/browse', :to => 'pages#browse'

  match '/mobile', :to => 'pages#index'
  match '/fullsite', :to => 'pages#index'

  root :to => 'pages#index'

end

app/models/artist_member.rb
class ArtistMember < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/artist_members_controller.rb
class ArtistMembersController < ApplicationController

  layout :resolve_layout
  
  before_filter :check_signed_in!
  
private

  def resolve_layout
    case action_name
    when "show"
      return "left_nav"
    else
      return "page"
    end
  end

end

app/helpers/artist_members_helper.rb
module ArtistMembersHelper
end

app/views/artist_members/_form.html.erb
<%= form_for(@artist_member) do |f| %>
  <% if @artist_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist_member.errors.count, "error") %> prohibited this artist_member from being saved:</h2>

      <ul>
      <% @artist_member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artist_members/edit.html.erb
<h1>Editing artist_member</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist_member %> |
<%= link_to 'Back', artist_members_path %>

app/views/artist_members/index.html.erb
<h1>Listing artist_members</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @artist_members.each do |artist_member| %>
  <tr>
    <td><%= link_to 'Show', artist_member %></td>
    <td><%= link_to 'Edit', edit_artist_member_path(artist_member) %></td>
    <td><%= link_to 'Destroy', artist_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Artist member', new_artist_member_path %>

app/views/artist_members/new.html.erb
<h1>New artist_member</h1>

<%= render 'form' %>

<%= link_to 'Back', artist_members_path %>

app/views/artist_members/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_artist_member_path(@artist_member) %> |
<%= link_to 'Back', artist_members_path %>