config/routes.rb
Jukebox::Application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => "users/registrations" } do
    get 'signout' => 'devise/sessions#destroy'
  end

  match '/accept_friend', :to => 'users#accept_friend'
  match '/accept_friend/:id', :to => 'users#accept_friend'

  resources :users do
    collection do
      get :friend_requests
      get :check_friend_request
      get :search
    end
    member do
    end
  end

  resources :releases

  resources :artist_members

  resources :artists do
    member do
      get   :tracks
    end
  end

  resources :tracks, :path => "songs" do
    collection do
      get   :upload
      post  :import
    end
    member do
      get   :details
    end
  end

  resources :albums do
    member do
      get   :tracks
    end
  end

  match '/albums/:name/:uqid', :to => 'albums#show'
  
  resources :playlists do
    collection do
      get   :selector
      post  :add_new
    end
    member do
      post  :add_track
      post  :remove_track
      get   :tracks
    end
  end

  match '/account', :to => 'account#index'
  match '/account/password', :to => 'account#password'
  match '/account/photo', :to => 'account#photo'
  match '/account/friends', :to => 'account#friends'
  match '/account/invite_friend', :to => 'account#invite_friend'

  match '/request_invite', :to => "pages#request_invite"
  match '/accept_invite', :to => "pages#accept_invite"
  match '/accept_invite/:token', :to => "pages#accept_invite"
  match '/home', :to => 'pages#home'
  match '/thanks', :to => 'pages#thanks'
  match '/library', :to => 'pages#home'
  match '/search', :to => 'pages#search'
  match '/browse', :to => 'pages#browse'

  match '/mobile', :to => 'pages#index'
  match '/fullsite', :to => 'pages#index'

  root :to => 'pages#index'

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base

  include ModelHelper
  
  attr_accessible :name, :user_id, :order_no, :personal, :list_type
  
  has_many :playlist_tracks, :dependent => :destroy
  has_many :tracks, :through => :playlist_tracks, :order => "order_no"

  before_create :set_uqid

  TYPE_FAVORITE         = 24
  TYPE_RECENT_PLAYED    = 32
  TYPE_MOST_PLAYED      = 36
  TYPE_FRIENDS_PLAYED   = 64
  TYPE_DEFAULT          = 100
  
  ADDABLE_LISTS = [TYPE_FAVORITE, TYPE_DEFAULT]
  
  def display_name
    list_type < 100 ? I18n.t(name) : name
  end
  
  def syslist?
    list_type < 100
  end
  
  def icon
    case list_type
    when TYPE_FAVORITE
      return "star"
    when TYPE_RECENT_PLAYED, TYPE_MOST_PLAYED
      return "fire"
    when TYPE_FRIENDS_PLAYED
      return "friends"
    else
      return "playlist"
    end
  end
  
private

  def set_uqid
    self.uqid = gen_unique_key_for_model(16)
    self.url = "/t/" + self.uqid
  end

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  
  include PlaylistsHelper

  layout :resolve_layout
  
  before_filter :check_signed_in!
  
  def add_track
    # TODO: check playlist can edit
    track = Track.find_by_uqid(params[:trkid])
    playlist = Playlist.find(params[:id])
    pl_track = PlaylistTrack.where("playlist_id = ? and track_id = ?", params[:id], track.id).first
    max_plt = PlaylistTrack.where("playlist_id = ?", params[:id]).order("order_no desc").first
    order_no = 1 if max_plt == nil
    order_no = max_plt.order_no + 1 if max_plt != nil
    if pl_track == nil
      pl_track = PlaylistTrack.new
      pl_track.playlist_id = params[:id]
      pl_track.track_id = track.id
      pl_track.order_no = order_no
      pl_track.save!
    end
    render json: { status: 200, :message => t("txt.trk_added_pl", :track => track.title, :playlist => playlist.display_name)}
  end
  
  def remove_track
    # TODO: check playlist can edit
    playlist = Playlist.find_by_uqid(params[:id])
    track = Track.find_by_uqid(params[:trkid])
    if playlist != nil && track != nil && can_edit_playlist(playlist)
      pl_track = PlaylistTrack.where("playlist_id = ? and track_id = ?", playlist.id, track.id).first
      pl_track.destroy
    end
    render json: { :status => 200, :message => "deleted" }
  end

  def add_album
    
  end
  
  def tracks
    if params[:uqid].present?
      @playlist = Playlist.find_by_uqid(params[:uqid])
    else
      @playlist = Playlist.find_by_uqid(params[:id])
    end
    render "playlists/tracks", :layout => false
  end

  def index
    @playlists = Playlist.where("user_id = ?", current_user.id).order("order_no")
    if request.headers["top-menu"]
      render "playlists/index", :layout => "left_nav_partial"
    else
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @playlists }
      end
    end
  end

private

  def resolve_layout
    return "left_nav"
  end

end

app/helpers/playlists_helper.rb
module PlaylistsHelper

  def can_edit_playlist(pl)
    user_signed_in? && pl.user_id == current_user.id
  end
  
  def playlist_tracks(playlist)
    if playlist.list_type == Playlist::TYPE_RECENT_PLAYED
      user_tracks = UserTrack.all(:include => :track,
                                  :conditions => ["user_id = ? and last_played_at is not null", current_user.id],
                                  :order => "last_played_at desc")
      user_tracks.map(&:track)
    elsif playlist.list_type == Playlist::TYPE_MOST_PLAYED
      Track.where("user_id = ? and play_count > 0", current_user.id).order("play_count desc")
    else
      playlist.tracks
    end
  end

end

app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>
  <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% @playlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/playlists/_lm_item.html.erb
<li><a id="ln<%= pl.uqid %>" data-id="<%= pl.uqid %>" data-title="<%= pl.display_name %>" href="<%= tracks_playlist_path(pl.uqid) %>" class="lnav-menu"><i class="icon-small icon-<%= pl.icon %>"></i> <%= pl.display_name %></a></li>

app/views/playlists/_show_w.html.erb
<% tracks = playlist_tracks(@playlist) %>
<div class="disbl p20 bdrb bg-w">
  <div class="distb w100">
    <div class="distc"><i class="icon-<%= @playlist.icon %>"></i></div>
    <div class="distc w100 pl20">
      <div class="distb w100">
        <div class="distc w100">
          <span class="disbl fntw-b fnts-m1" style="margin-top:3px;"><%= @playlist.display_name %></span>
          <span class="disbl"><%= t("counts.tracks", :count => tracks.count) %></span>
        </div>
        <div class="distc nowrap">
          <a class="play-playlist tipt" href="javascript:;" title="<%= t("label.play") %>"><i class="icon-play"></i>
          <% if !@playlist.syslist? %>
          </a><a class="del-playlist tipt" href="javascript:;" title="<%= t("label.delete") %>"><i class="icon-trash"></i>
          <% end %>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="disbl">
  <%= render "tracks/grid", :tracks => tracks, :nobdr => true, :showDelete => can_edit_playlist(@playlist) %>
</div>
<script>
$(document).ready(function() {
  $(".trklst .del").click(function() {
    $(this).tooltip("destroy");
    var trkid = $(this).attr("data-id");
    $.ajax({
      url: "<%= remove_track_playlist_path(@playlist.uqid) %>",
      type: "POST",
      data: { trkid: trkid },
      headers: { 'X-CSRF-Token': '<%= form_authenticity_token.to_s %>' },
      success: function(data) {
        alert("removed from playlist");
        $("#track_" + trkid).remove();
      }
    });
    return false;
  });
});
</script>

app/views/playlists/edit.html.erb
<h1>Editing playlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

app/views/playlists/index.html.erb
<% @title = t("label.artists") %>
<% content_for :left_nav do %>
<div class="disbl pt10">
<ul class="nav nav-list">
  <li class="nav-header"><%= t("label.playlists") %></li>
  <% @playlists.each do |pl| %>
  <%= render "playlists/lm_item", :pl => pl %>
  <% end %>
  <li><a href="" class="add-new-pl fntc-gr"><i class="icon-small icon-plus trn50"></i> <%= t("label.new_playlist") %></a>
    <%= form_tag add_new_playlists_path do %>
    <%= text_field_tag :name, nil, :placeholder => t("label.enter_playlist_name"), :id => "new_pl_name", :class => "input-thin", :style => "width:170px;display:none;margin-bottom:0;" %>
    <% end %>
  </li>
</ul>
</div>
<% end %>

app/views/playlists/lm_item.html.erb
<%= render "playlists/lm_item", :pl => @playlist %>

app/views/playlists/new.html.erb
<h1>New playlist</h1>

<%= render 'form' %>

<%= link_to 'Back', playlists_path %>

app/views/playlists/selector.html.erb
<ul class="polnks">
  <% @playlists.each do |pl| %>
  <li><a href="javascript:;" class="pl-add-track" data-id="<%= pl.id %>"><%= pl.name %></a></li>
  <% end %>
</ul>

app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_playlist_path(@playlist) %> |
<%= link_to 'Back', playlists_path %>

app/views/playlists/tracks.html.erb
<%= render "playlists/show_w" %>