config/routes.rb
Jukebox::Application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => "users/registrations" } do
    get 'signout' => 'devise/sessions#destroy'
  end

  match '/accept_friend', :to => 'users#accept_friend'
  match '/accept_friend/:id', :to => 'users#accept_friend'

  resources :users do
    collection do
      get :friend_requests
      get :check_friend_request
      get :search
    end
    member do
    end
  end

  resources :releases

  resources :artist_members

  resources :artists do
    member do
      get   :tracks
    end
  end

  resources :tracks, :path => "songs" do
    collection do
      get   :upload
      post  :import
    end
    member do
      get   :details
    end
  end

  resources :albums do
    member do
      get   :tracks
    end
  end

  match '/albums/:name/:uqid', :to => 'albums#show'
  
  resources :playlists do
    collection do
      get   :selector
      post  :add_new
    end
    member do
      post  :add_track
      post  :remove_track
      get   :tracks
    end
  end

  match '/account', :to => 'account#index'
  match '/account/password', :to => 'account#password'
  match '/account/photo', :to => 'account#photo'
  match '/account/friends', :to => 'account#friends'
  match '/account/invite_friend', :to => 'account#invite_friend'

  match '/request_invite', :to => "pages#request_invite"
  match '/accept_invite', :to => "pages#accept_invite"
  match '/accept_invite/:token', :to => "pages#accept_invite"
  match '/home', :to => 'pages#home'
  match '/thanks', :to => 'pages#thanks'
  match '/library', :to => 'pages#home'
  match '/search', :to => 'pages#search'
  match '/browse', :to => 'pages#browse'

  match '/mobile', :to => 'pages#index'
  match '/fullsite', :to => 'pages#index'

  root :to => 'pages#index'

end

app/views/layouts/_footer.html.erb
<div class="footer <%= @homePage ? "footer-bottom" : "" %>">
  <span>&copy; 2013 Miliea</span>
  <% if !user_signed_in? %>
  <div class="pull-right">
  <% end %>
  <span>Privacy</span>
  <span>Terms</span>
  <% if !user_signed_in? %>
  </div>
  <% end %>
  <% if user_signed_in? %>
  <div class="pull-right">
    <span><a href="<%= signout_path %>"><%= t("label.sign_out") %></a></span>
  </div>
  <% end %>
</div>

app/views/layouts/_head.html.erb
<% ts = "20130430" %>
<head>
<title><%= @title + " - " + t("title") %></title>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= stylesheet_link_tag APP_CONFIG['cdn_base_url'] + "/bootstrap/css/bootstrap.min.css?" + ts %>
<%= stylesheet_link_tag APP_CONFIG['cdn_base_url'] + "/bootstrap/css/bootstrap-responsive.min.css?" + ts %>
<%= stylesheet_link_tag APP_CONFIG['cdn_base_url'] + "/css/base.css?" + ts %>
<%= stylesheet_link_tag APP_CONFIG['cdn_base_url'] + "/css/app.css?" + ts %>
<%= stylesheet_link_tag APP_CONFIG['cdn_base_url'] + "/css/player.css?" + ts %>
<% if @custom_css_files != nil %><% @custom_css_files.each do |f| %>
<%= stylesheet_link_tag APP_CONFIG['cdn_base_url'] + "/css/" + f + ".css?" + ts %>
<% end %><% end %>
<%= javascript_include_tag "application" %>
<%= javascript_include_tag APP_CONFIG['cdn_base_url'] + "/js/common.js" %>
<%= javascript_include_tag APP_CONFIG['cdn_base_url'] + "/js/jquery.min.js" %>
<%= javascript_include_tag APP_CONFIG['cdn_base_url'] + "/js/jquery.jplayer.min.js" %>
<%= javascript_include_tag APP_CONFIG['cdn_base_url'] + "/bootstrap/js/bootstrap.min.js" %>
<%= csrf_meta_tags %>
<%= yield(:head) %>
</head>

app/views/layouts/_topbar.html.erb
<div class="tbc <%= (defined? style) ? style : "" %>"><div class="container"><div class="tb">
  <div class="w100"><a href="<%= root_path %>"><%= image_tag APP_CONFIG['cdn_base_url'] + "/images/logo-m.png" %></a></div>
  <div>
    <div class="navbar navbar-inverse">
      <ul class="nav pull-right">
        <li><%= link_to t("label.browse"), browse_path, :title => t("label.browse"), :class => "tipno" %></a></li>
        <% if !user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t("label.log_in") %></a>
          <ul class="dropdown-menu tli">
            <li>
              <div class="tlif"><div class="tli">
<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
<div class="disbl"><%= f.text_field :email, :placeholder => t("label.email") %></div>
<div class="disbl"><%= f.password_field :password, :placeholder => t("label.password") %></div>
<div class="disbl"><label class="checkbox"><%= f.check_box :remember_me %><%= t("label.remember_me")%></label></div>
<div class="disbl"><%= f.submit t("label.log_in"), :class => "btn btn-info w100" %></div>
<% end %>
<div class="disbl mt10 tac"><a href="<%= new_user_password_path %>"><%= t("label.forgot_password")%></a></div>
              </div><div class="tsu">
                <span class="disbl"><%= t("txt.no_acc") %></span>
                <span class="disbl"><%= link_to t("label.signup_here"), new_user_registration_path %></a></span>
              </div></div>
            </li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
  <% if user_signed_in? %>
  <div>
    <div class="navbar navbar-inverse">
      <ul class="nav pull-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-white icon-user"></i></a>
          <ul class="dropdown-menu tmn">
            <li><a href="<%= signout_path %>"><%= t("label.sign_out") %></a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
  <% end %>
  <% if !user_signed_in? %>
  <div><a href="<%= new_registration_path(resource_name) %>" class="btn btn-info"><%= t("label.get_prod")%></a></div>
  <% end %>
</div></div></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render "layouts/head" %>
<body class="<%= @customBodyClass %>">
<%= yield(:topbar) %>
<div class="container <%= !@homePage ? "mp" : "" %>">
<%= yield(:content) %>
</div>
<div class="<%= @homePage ? "footer-bottom" : "" %>"><div class="container">
<%= render 'layouts/footer' %>
</div></div>
<script>
$(document).ready(function() {
  jkCommon.init();
});
$(document).bind("ready ajaxComplete", function() {
  jkCommon.initAjax();
});
</script>
</body>
</html>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html>
<%= render "layouts/head" %>
<style>
body {
  background: #FFFFFF;
  padding: 0;
  margin: 0;
}
</style>
<body>
<%= yield %>
<script>
$(document).ready(function() {
  jkCommon.init();
});
$(document).bind("ready ajaxComplete", function() {
  jkCommon.initAjax();
});
</script>
</body>
</html>

app/views/layouts/email_layout_1.html.erb
<%= yield %>

app/views/layouts/email_layout_text.html.erb
<%= yield %>

app/views/layouts/home.html.erb
<% content_for :topbar do %>
<%= render "layouts/topbar", :style => "home-tbc" %>
<% end %>
<% content_for :content do %>
<%= yield %>
<% end %>
<%= render :file => 'layouts/application' %>

app/views/layouts/left_menu.html.erb
<% content_for :main_content do %>
<div class="distb">
<div class="distc vat" style="background-color:#D5D5D5;"><div class="disbl" style="width:240px;min-height:600px;"><%= yield(:left_menu) %></div></div>
<div class="distc w100"><div class="disbl"><%= yield %></div></div>
</div>
<% end %>
<%= render :file => 'layouts/main' %>

app/views/layouts/left_nav.html.erb
<% content_for :page_content do %>
<div class="distb lnav">
  <div class="distc ltnav vat"><div><%= yield(:left_nav) %></div></div>
  <div class="distc w100 vat"><div id="lib_content" class="disbl"><%= yield %></div></div>
</div>
<script>
$(document).bind("ready ajaxComplete", function() {
  $(".lnav-menu").unbind("click");
  $(".lnav-menu").click(function() {
    jkCommon.loadLeftNavBody($(this));
    jkCommon.setPageTitle($(this).attr("data-title"));
    return false;
  });
});
</script>
<% end %>
<%= render :file => 'layouts/page' %>

app/views/layouts/left_nav_partial.html.erb
<div class="distb lnav">
  <div class="distc ltnav vat"><div><%= yield(:left_nav) %></div></div>
  <div class="distc w100 vat"><div id="lib_content" class="disbl"><%= yield %></div></div>
</div>

app/views/layouts/main.html.erb
<% content_for :topbar do %>
<%= render "layouts/topbar" %>
<% end %>
<% content_for :content do %>
<%= render "shared/top_player" %>
<%= content_for?(:main_content) ? yield(:main_content) : yield %>
<% end %>
<%= render :file => 'layouts/application' %>

app/views/layouts/page.html.erb
<!DOCTYPE html>
<html>
<%= render "layouts/head" %>
<body class="<%= @customBodyClass %>" style="padding-top:0;">
<div class="container"><div class="p10"><div class="mainp <%= @customMainClass %>"><div class="content">
  <div class="topp">
    <% if user_signed_in? %>
    <div class="logo hide ml-play"><%= image_tag APP_CONFIG['cdn_base_url'] + "/images/logo-main-l.png" %></div>
    <% end %>
    <div class="play">
      <div class="logo ml-no-play"><%= image_tag APP_CONFIG['cdn_base_url'] + "/images/logo-main-l.png" %></div>
      <% if user_signed_in? %>
      <div class="player ml-play" style="display:none;">
        <div class="art"><div><img src=""></img></div></div>
        <div class="dtls">
          <span class="ttl"></span>
          <span class="info"></span>
        </div>
        <div id="player_1" class="jp-jplayer"></div>
        <div id="jp_container_1" class="jp-audio">
          <ul class="jp-controls">
            <li><a href="javascript:;" class="jp-play icon-play" tabindex="1">play</a></li>
            <li><a href="javascript:;" class="jp-pause icon-pause" tabindex="1">pause</a></li>
            <li><a href="javascript:;" class="jp-stop icon-stop" tabindex="1">stop</a></li>
            <li><a href="javascript:;" class="jp-mute icon-small icon-vol-low" tabindex="1">mute</a></li>
            <li><a href="javascript:;" class="jp-volume-max icon-small icon-vol-high" tabindex="1">max volume</a></li>
          </ul>
          <div class="jp-progress">
            <div class="jp-seek-bar">
              <div class="jp-play-bar"></div>
            </div>
          </div>
          <div class="jp-time-holder">
            <div class="jp-current-time"></div>
            <div class="jp-duration"></div>
          </div>
          <div class="jp-volume-bar">
            <div class="jp-volume-bar-value"></div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <% if user_signed_in? %>
    <a href="<%= account_path %>" class="usp">
      <%= image_tag current_user.photo.url(:m), :alt => current_user.name %>
    </a>
    <% end %>
  </div>
  <% if user_signed_in? %>
  <div class="topm">
    <div class="lmn">
      <a href="<%= upload_tracks_path %>" class="btn btn-inverse upb mr10 import-music"><%= t("label.import_music") %>
      </a><div class="dropdown disib">
        <a id="tmn_fr_dd" class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-user"></i><label id="tmn_fr_cnt" class="badge hide">0</label></a>
        <div class="dropdown-menu" role="menu">
          <div class="hdr"><%= raw t("txt.friend_requests", :count => "<span class=\"fr-cnt\"></span>")%></div>
          <div id="tmn_fr_ddc"></div>
        </div>
      </div><div class="dropdown disib ml10">
        <a id="tmn_shared_dd" class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-album"></i><label id="tmn_shared_cnt" class="badge">0</label></a>
        <div class="dropdown-menu" role="menu">
          <div class="hdr"><%= raw t("txt.friend_requests", :count => "<span class=\"fr-cnt\"></span>")%></div>
          <div id="tmn_shared_ddc"></div>
        </div>
      </div>
    </div>
    <ul class="mns">
      <li class="<%= @tmenu == "library" ? "active" : "" %>"><a href="<%= library_url %>" class="mn-menu"><%= t("label.library") %></a></li>
      <li class="<%= @tmenu == "tracks" ? "active" : "" %>"><a href="<%= tracks_url %>" class="mn-menu"><%= t("label.tracks") %></a></li>
      <li class="<%= @tmenu == "albums" ? "active" : "" %>"><a href="<%= albums_url %>" class="mn-menu"><%= t("label.albums") %></a></li>
      <li class="<%= @tmenu == "artists" ? "active" : "" %>"><a href="<%= artists_url %>" class="mn-menu"><%= t("label.artists") %></a></li>
      <li class="<%= @tmenu == "playlists" ? "active" : "" %>"><a href="<%= playlists_url %>" class="mn-menu"><%= t("label.playlists") %></a></li>
    </ul>
    <div class="sch">
      <%= text_field_tag :term, params[:term], :placeholder => t("label.search") %>
    </div>
  </div>
  <% end %>
<div class="topfsh" style="display:none;"><a href="javascript:;" class="close" data-dismiss="topfsh">&times;</a></div>
<div id="main_content"><%= content_for?(:page_content) ? yield(:page_content) : yield %></div>
</div>
<%= render "layouts/footer" %>
</div></div></div>
<script>
$(document).ready(function() {
  <% if user_signed_in? %>
  $("#player_1").jPlayer({
    swfPath: "<%= APP_CONFIG['cdn_base_url'] %>/jquery",
    supplied: "mp3",
    wmode: "window"
  });
  $("#player_1").bind($.jPlayer.event.ended, function(event) {
    $(".trklst li").removeClass("playing");
    setTimeout(function(){ $("#track_" + $(".player").attr("data-track")).next().find(".play-track").click() }, 1000);
  });
  <% end %>
  $("body").click(function() {
    jkCommon.destroyTrackPopover();
  });
  $(".mn-menu").unbind("click");
  $(".mn-menu").click(function() {
    var menu = $(this);
    $.ajax({
      url: menu.attr("href"),
      headers: { "top-menu": true },
      success: function(data) {
        $("#main_content").html(data);
        $(".mn-menu").closest("li").removeClass("active");
        menu.closest("li").addClass("active");
        jkCommon.setPageTitle(menu.text());
      }
    });
    return false;
  });
  <% if flash[:top_flash] %>
  jkCommon.showTopFlash("<%= flash[:top_flash] %>");
  <% end %>
  <% if user_signed_in? %>
  jkCommon.checkFriendRequest();
  <% end %>
});
$(document).bind("ready ajaxComplete", function() {
  <% if user_signed_in? %>
  $(".play-track").unbind("click");
  $(".play-track").click(function() {
    jkCommon.playTrack($(this).attr("data-id"));
    return false;
  });
  $("ul.trklst > li > div .mre").unbind("click");
  $("ul.trklst > li > div .mre").click(function() {
    if ($(this).hasClass("ppo")) {
      jkCommon.destroyTrackPopover();
    } else {
      var id = $(this).closest("li").find(".play-track").attr("data-id");
      $("#pl_trk_id").val(id);
      jkCommon.destroyTrackPopover();
      $(this).addClass("ppo");
      $(this).popover({
        placement: 'right',
        title: '<span class="pr10"><%= t("label.add_to_playlist") %></span><a href=\"#\" class=\"close\">&times;</a>',
        trigger: 'click',
        html: true,
        container: 'body',
        content: function() {
          return $("#po_playlists").html();
        }
      });
      $(this).popover('show');
      $(".popover .close").click(function() {
        jkCommon.destroyTrackPopover();
        return false;
      });
      $(".pl-add-track").click(function() {
        jkCommon.destroyTrackPopover();
        var plId = $(this).attr("data-id");
        $.ajax({
          url: "<%= playlists_path %>/" + plId + "/add_track",
          type: "POST",
          data: { trkid: $("#pl_trk_id").val() },
          headers: { 'X-CSRF-Token': '<%= form_authenticity_token.to_s %>' },
          success: function(data) {
            jkCommon.showTopFlash(data.message);
          }
        })
        return false;
      });
    }
    event.stopPropagation();
    return false;
  });
  $("#new_pl_name").unbind("focus click");
  $("#new_pl_name").bind("focus click", function() {
    return false;
  });
  <% end %>
  jkCommon.init();
  jkCommon.initAjax();
  jkCommon.loadHashLeftNav();
});
</script>
<% if user_signed_in? %>
<div class="hide" id="po_playlists">
  <%= hidden_field_tag :track, nil, :id => "pl_trk_id" %>
  <ul class="polnks">
  <% my_playlists.each do |pl| %>
  <li><a href="#" class="pl-add-track" data-id="<%= pl.id %>"><%= pl.display_name %></a></li>
  <% end %>
</ul></div>
<% end %>
</body>
</html>